ParallelDevs\ProjectManagementBundle\Entity\Phases:
    type: entity
    table: phases
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
            default: ''
        defaultValues:
            type: text
            nullable: false
            length: null
            fixed: false
            comment: ''
            column: default_values
    lifecycleCallbacks: {  }
