ParallelDevs\ProjectManagementBundle\Entity\ProjectsStatus:
    type: entity
    table: projects_status
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
            default: ''
        sortOrder:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
            default: '0'
            column: sort_order
        defaultValue:
            type: boolean
            nullable: true
            comment: ''
            column: default_value
        active:
            type: boolean
            nullable: true
            comment: ''
    lifecycleCallbacks: {  }
