ParallelDevs\ProjectManagementBundle\Entity\TasksGroups:
    type: entity
    table: tasks_groups
    indexes:
        fk_tasks_groups_projects:
            columns:
                - projects_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
            default: ''
    manyToOne:
        projects:
            targetEntity: Projects
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                projects_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
