ParallelDevs\ProjectManagementBundle\Entity\Tickets:
    type: entity
    table: tickets
    indexes:
        fk_tickets_users:
            columns:
                - users_id
        fk_tickets_tickets_status:
            columns:
                - tickets_status_id
        fk_tickets_tickets_types:
            columns:
                - tickets_types_id
        fk_tickets_projects:
            columns:
                - projects_id
        fk_tickets_departments:
            columns:
                - departments_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
            default: ''
        description:
            type: text
            nullable: true
            length: null
            fixed: false
            comment: ''
        createdAt:
            type: datetime
            nullable: true
            comment: ''
            column: created_at
    manyToOne:
        ticketsStatus:
            targetEntity: TicketsStatus
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                tickets_status_id:
                    referencedColumnName: id
            orphanRemoval: false
        ticketsTypes:
            targetEntity: TicketsTypes
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                tickets_types_id:
                    referencedColumnName: id
            orphanRemoval: false
        users:
            targetEntity: Users
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                users_id:
                    referencedColumnName: id
            orphanRemoval: false
        projects:
            targetEntity: Projects
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                projects_id:
                    referencedColumnName: id
            orphanRemoval: false
        departments:
            targetEntity: Departments
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                departments_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
