ParallelDevs\ProjectManagementBundle\Entity\UsersGroups:
    type: entity
    table: users_groups
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
            default: ''
        allowViewAll:
            type: boolean
            nullable: true
            comment: ''
            column: allow_view_all
        allowManageProjects:
            type: boolean
            nullable: true
            comment: ''
            column: allow_manage_projects
        allowManageTasks:
            type: boolean
            nullable: true
            comment: ''
            column: allow_manage_tasks
        allowManageTickets:
            type: boolean
            nullable: true
            comment: ''
            column: allow_manage_tickets
        allowManageUsers:
            type: boolean
            nullable: true
            comment: ''
            column: allow_manage_users
        allowManageConfiguration:
            type: boolean
            nullable: true
            comment: ''
            column: allow_manage_configuration
        allowManageTasksViewonly:
            type: boolean
            nullable: true
            comment: ''
            column: allow_manage_tasks_viewonly
        allowManageDiscussions:
            type: boolean
            nullable: true
            comment: ''
            column: allow_manage_discussions
        allowManageDiscussionsViewonly:
            type: boolean
            nullable: true
            comment: ''
            column: allow_manage_discussions_viewonly
    lifecycleCallbacks: {  }
