sudo: false

language: php

php:
    - 5.5
    - 5.6
    - 7.0
sudo: false
cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - mysql -e "create database IF NOT EXISTS pdevspm;" -uroot
  - cp app/config/parameters.yml.travis app/config/parameters.yml
  - composer self-update
  - composer install
  - php bin/console doctrine:schema:create --env=test
  - php bin/console doctrine:fixtures:load -n --env=test

script:
  - phpunit

notifications:
  email:
    -  d.noyola@paralleldevs.com
  on_success: change
  on_failure: always
