# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    app.form.registration:
        class: AppBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: app_user_registration }
    app.form.group:
        class: AppBundle\Form\GroupType
        tags:
            - { name: form.type, alias: app_user_group }

    # Voters
    app.post_voter:
        class: AppBundle\Security\ProjectVoter
        tags:
            - { name: security.voter }
        public: false
    app.configuration:
        class: AppBundle\Security\ConfigurationVoter
        tags:
            - { name: security.voter }
        public: false
