AppBundle\Entity\Attachments:
    type: entity
    table: attachments
    uniqueConstraints:
        id:
            columns:
                - id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        bindType:
            type: string
            nullable: false
            length: 64
            fixed: false
            comment: ''
            default: ''
            column: bind_type
        bindId:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            default: '0'
            column: bind_id
        file:
            type: string
            nullable: true
            length: 255
            fixed: false
            comment: ''
        info:
            type: string
            nullable: true
            length: 255
            fixed: false
            comment: ''
    lifecycleCallbacks: {  }
