AppBundle\Entity\Configuration:
    type: entity
    table: configuration
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        key:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        value:
            type: string
            nullable: true
            length: 255
            fixed: false
            comment: ''
    lifecycleCallbacks: {  }
