AppBundle\Entity\ExtraFieldsList:
    type: entity
    table: extra_fields_list
    indexes:
        fk_extra_fields_list_extra_fields:
            columns:
                - extra_fields_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        bindId:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            default: '0'
            column: bind_id
        value:
            type: text
            nullable: false
            length: null
            fixed: false
            comment: ''
    manyToOne:
        extraFields:
            targetEntity: ExtraFields
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                extra_fields_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
