AppBundle\Entity\Projects:
    type: entity
    table: projects
    indexes:
        fk_projects_projects_status:
            columns:
                - projects_status_id
        fk_projects_project_types:
            columns:
                - projects_types_id
        fk_projects_pople:
            columns:
                - created_by
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
            default: ''
        description:
            type: text
            nullable: true
            length: null
            fixed: false
            comment: ''
        team:
            type: text
            nullable: true
            length: null
            fixed: false
            comment: ''
        createdAt:
            type: datetime
            nullable: true
            comment: ''
            column: created_at
        orderTasksBy:
            type: string
            nullable: true
            length: 64
            fixed: false
            comment: ''
            column: order_tasks_by
    manyToOne:
        projectsStatus:
            targetEntity: ProjectsStatus
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                projects_status_id:
                    referencedColumnName: id
            orphanRemoval: false
        projectsTypes:
            targetEntity: ProjectsTypes
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                projects_types_id:
                    referencedColumnName: id
            orphanRemoval: false
        createdBy:
            targetEntity: Users
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                created_by:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
