AppBundle\Entity\Tasks:
    type: entity
    table: tasks
    indexes:
        fk_tasks_projects:
            columns:
                - projects_id
        fk_tasks_task_status:
            columns:
                - tasks_status_id
        fk_tasks_task_type:
            columns:
                - tasks_type_id
        fk_tasks_task_label:
            columns:
                - tasks_label_id
        fk_tasks_projects_phases:
            columns:
                - projects_phases_id
        fk_tasks_pople:
            columns:
                - created_by
        fk_tasks_tasks_groups:
            columns:
                - tasks_groups_id
        fk_tasks_versions:
            columns:
                - versions_id
        fk_tasks_tasks_priority:
            columns:
                - tasks_priority_id
        fk_tasks_tickets:
            columns:
                - tickets_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
            default: ''
        description:
            type: text
            nullable: true
            length: null
            fixed: false
            comment: ''
        assignedTo:
            type: string
            nullable: true
            length: 255
            fixed: false
            comment: ''
            column: assigned_to
        estimatedTime:
            type: float
            nullable: true
            precision: 10
            scale: 0
            comment: ''
            column: estimated_time
        dueDate:
            type: date
            nullable: true
            comment: ''
            column: due_date
        createdAt:
            type: datetime
            nullable: true
            comment: ''
            column: created_at
        closedDate:
            type: date
            nullable: true
            comment: ''
            column: closed_date
        discussionId:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
            column: discussion_id
        startDate:
            type: date
            nullable: true
            comment: ''
            column: start_date
        progress:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
    manyToOne:
        projects:
            targetEntity: Projects
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                projects_id:
                    referencedColumnName: id
            orphanRemoval: false
        tickets:
            targetEntity: Tickets
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                tickets_id:
                    referencedColumnName: id
            orphanRemoval: false
        tasksStatus:
            targetEntity: TasksStatus
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                tasks_status_id:
                    referencedColumnName: id
            orphanRemoval: false
        tasksPriority:
            targetEntity: TasksPriority
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                tasks_priority_id:
                    referencedColumnName: id
            orphanRemoval: false
        tasksType:
            targetEntity: TasksTypes
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                tasks_type_id:
                    referencedColumnName: id
            orphanRemoval: false
        tasksLabel:
            targetEntity: TasksLabels
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                tasks_label_id:
                    referencedColumnName: id
            orphanRemoval: false
        tasksGroups:
            targetEntity: TasksGroups
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                tasks_groups_id:
                    referencedColumnName: id
            orphanRemoval: false
        projectsPhases:
            targetEntity: ProjectsPhases
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                projects_phases_id:
                    referencedColumnName: id
            orphanRemoval: false
        versions:
            targetEntity: Versions
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                versions_id:
                    referencedColumnName: id
            orphanRemoval: false
        createdBy:
            targetEntity: Users
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                created_by:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
