AppBundle\Entity\Versions:
    type: entity
    table: versions
    indexes:
        fk_versions_versions_status:
            columns:
                - versions_status_id
        fk_versions_projects:
            columns:
                - projects_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
            default: ''
        description:
            type: text
            nullable: true
            length: null
            fixed: false
            comment: ''
        dueDate:
            type: date
            nullable: true
            comment: ''
            column: due_date
    manyToOne:
        projects:
            targetEntity: Projects
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                projects_id:
                    referencedColumnName: id
            orphanRemoval: false
        versionsStatus:
            targetEntity: VersionsStatus
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                versions_status_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
